[build]
  publish = "build" # Change this if your build output directory is different
  command = "npm run build" # Change this if your build command is different

[[redirects]]
  from = "/*"
  to = "/"
  status = 200
  force = true
